version: '2'

services:

  elasticsearch:
    build: elasticsearch/
    container_name: elasticsearch
    environment:
      node.name: elasticsearch
      ES_JAVA_OPTS: "-Xmx1024m -Xms1024m"
      discovery.type: "zen"
      discovery.zen.ping.unicast.hosts: "elasticsearch2,elasticsearch3"

  elasticsearch2:
    build: elasticsearch/
    container_name: elasticsearch2
    environment:
      node.name: elasticsearch2
      ES_JAVA_OPTS: "-Xmx1024m -Xms1024m"
      discovery.type: "zen"
      discovery.zen.ping.unicast.hosts: "elasticsearch,elasticsearch3"

  elasticsearch3:
    build: elasticsearch/
    container_name: elasticsearch3
    environment:
      node.name: elasticsearch3
      ES_JAVA_OPTS: "-Xmx1024m -Xms1024m"
      discovery.type: "zen"
      discovery.zen.ping.unicast.hosts: "elasticsearch,elasticsearch2"

  kibana:
    build: kibana/
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  cerebro:
    build: cerebro/
    container_name: cerebro
    ports:
      - "9000:9000"
    depends_on:
      - elasticsearch

  elasticsearchhq:
    image: elastichq/elasticsearch-hq
    container_name: elasticsearchhq
    ports:
      - "5000:5000"
    environment:
      HQ_DEFAULT_URL: 'http://elasticsearch:9200'
    depends_on:
      - elasticsearch

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

volumes:
  elasticsearch-data:
    driver: local
  elasticsearch-backup:
    driver: local
